[package]
name = "rustlink-server"
version = "0.1.0"
authors = ["DaniÃ«l Louwrink <daniel.louwrink@gmail.com>"]

[dependencies]
rustlink = { path = "rustlink" }
jsonrpc-core = { git = "https://github.com/ocecaco/jsonrpc" }
jsonrpc-macros = { git = "https://github.com/ocecaco/jsonrpc" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
error-chain = "0.10"
log = "0.3"
env_logger = "0.4"
backtrace = { version = "0.3", features = ["serialize-serde"] }
